config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', home: 'home' }
	  
  #RUTA DE REGISTRO  
    get "registroapi", to: "home#showregisterAPI", as: 'registershow'
    post "registroapi",  to: "home#sendregisterAPI", as: 'registershowsend'

  #RUTA DEL PERFIL DE USUARIO
    get "perfil", to: "home#showPerfil", as: "showPerfil"

  #RUTA DEL CARRITO 
    get "prepurchase", to: "home#prepurchase", as: "prepurchase" #Carro de compra
    post "producto/:id", to: "home#addCarro", as: "addcar" #Agregar al carro
    delete "producto/:id", to: "home#deleteCarro", as: "deletecar" #Eliminar del carro


  #RUTA DEL PRODUCTO
    get "producto/:id", to: "home#showProduct", as: "producto" #Producto individual

    post "addProducto", to: "home#addProducto", as: "addProducto" #Agrear un nuevo producto

    get "categoria/:categoria", to: "home#showCat", as: "showCat" #Filtrado por categoria

    get "orden/alfabeticamente/:id", to: "home#showAlfa", as: "showAlfabeticamente" #Filtrado alfabeticamente
   
    get "orden/precio/:id", to: "home#showPrec", as: "showPrecio" #Filtrado por precio

    delete "producto/:id/delete", to: "home#deleteProd", as:"deleteProducto" #Eliminacion del producto

    get "producto/:id/editar", to: "home#updateProdshow", as:"updateProductoShow" #Pantalla de edicion
    post "updateProducto", to: "home#updateProdsend", as: "updateProducto" #Edicion del producto


  #RUTA DE PAGO
    get "checkout", to: "home#mostrarCheckout", as: "mostrarCheckout" #Mostrar el checkout
    post "factura", to: "home#mostrarFactura", as: "mostrarFactura"

  #RUTA DE COMENTARIO
    post "createComentario", to: "home#createComentario", as: "createComentario" #Post nuevo comentario

  #RUTA DE BUSQUEDA
    get "busqueda", to: "home#busqueda", as: "nuevaBusqueda"
    
  #ROOT DE LA PAGINA
    root 'home#index', as: "root"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  $API_URL = "localhost:5000" #Url del API

  def index
  	vars = request.query_parameters
  	if user_signed_in?  
  		if session[:carro] == nil
  			session[:carro] = []
  		end
  	else
      session[:carro] = nil
    end

    if session[:alfabeticamente] == nil
    	session[:alfabeticamente] = 1
    end

    if session[:precio] == nil
    	session[:precio] = 1
    end

  	@products = JSON.parse(open("http://"+$API_URL+"/product").read, {:symbolize_names => true})

  	if vars['action_do'] == "succesfull_register"
  		flash.now["success"] = "Registro exitoso, por favor inicie sesión"

  	elsif vars['action_do'] == "succesfull_add"
  		flash.now["success"] = "Producto agregado al carro exitosamente"

  	elsif vars['action_do'] == "succesfull_delete"
		flash.now["success"] = "Producto eliminado del carro exitosamente"
  	
	elsif vars['action_do'] == "succesfull_addProduct"
		flash.now["success"] = "Producto creado exitosamente"

	elsif vars['action_do'] == "succesfull_deleteProduct"
		flash.now["success"] = "Producto eliminado exitosamente"

	elsif vars['action_do'] == "succesfull_editProduct"
		flash.now["success"] = "Producto editado exitosamente"

	elsif vars['action_do'] == "succesfull_addComment"
		flash.now["success"] = "Comentario agregado al diario de "+current_user.username
  	end	


  end




  def showregisterAPI
  	render(:action => 'registro')
  end


  def sendregisterAPI
  	#Realizo la peticion al API con los parametros introducidos
  	uri = URI('http://'+$API_URL+'/login')
	req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
	req.body = {email: params[:email], password: params[:password]}.to_json
	res = Net::HTTP.start(uri.hostname, uri.port) do |http|
		http.request(req)
	end
	data = JSON.parse(res.body) #Aqui esta la respuesta del API
	if(data['login_value']) #Se logeo correctamente
		hay_email = User.find_by_email(data['email'])
		if(!hay_email) #El usuario no existe
			@user = User.create(:email => data['email'], :password => data['password'], :password_confirmation => data['password'], 
								:nombre => data['nombre'], :apellido => data['apellido'], :username => data['username'],
								:fotoPerfil => data["fotoPerfil"], :genero => data['genero'], 
								:telefono => data['telefono'])
		end
	end
  	redirect_to controller: 'home', action: 'index', action_do: "succesfull_register"
  end

  def showPerfil

  	@comentarios = Comentario.where(:user_id => current_user.id)

  	render(:action => 'perfil')
  end

  def prepurchase
  	@data = []
  	if(session[:carro].size != 0)
	  	uri = URI('http://'+$API_URL+'/products')
		req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
		req.body = {ids: session[:carro]}.to_json
		res = Net::HTTP.start(uri.hostname, uri.port) do |http|
			http.request(req)
		end
		@data = JSON.parse(res.body) #Aqui esta la respuesta del API
	end

	for product_in_car in session[:carro]
		producto_esta = false
		for product_in_api in @data
			puts()
			if product_in_car == product_in_api['id']
				producto_esta = true
			end
		end
		if !producto_esta
			session[:carro].delete(product_in_car)
		end
	end

  	render(:action => 'precompra')
  end
  
  def showProduct
  	product_id = params[:id]
  	@product = JSON.parse(open("http://"+$API_URL+"/product/"+product_id).read, {:symbolize_names => true})
  	render(:action => 'product')
  end


  def addCarro
  	session[:carro].push((params[:id]).to_i)

  	redirect_to controller: 'home', action: 'index', action_do: "succesfull_add"

  end

  def deleteCarro
  	session[:carro].delete((params[:id]).to_i)
  	redirect_to controller: 'home', action: 'index', action_do: "succesfull_delete"

  end

  def addProducto
	uri = URI('http://'+$API_URL+'/product')
	req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
	req.body = {nombre: params[:nombre], precio: params[:precio], 
				foto: params[:foto], idCategoria: ((params[:idCategoria]).to_i), 
				descripcion: params[:descripcion]}.to_json
	res = Net::HTTP.start(uri.hostname, uri.port) do |http|
		http.request(req)
	end
	@data = JSON.parse(res.body) #Aqui esta la respuesta del API

	redirect_to controller: 'home', action: 'index', action_do: "succesfull_addProduct"
  end


  def showCat
	id_categoria = params[:categoria]
	@products = JSON.parse(open("http://"+$API_URL+"/categories/"+id_categoria).read, {:symbolize_names => true})
  	@category = id_categoria.to_i
 	
 	render(:action => 'showCategory')
  end

  def showAlfa
  	if session[:alfabeticamente] == 1
  		session[:alfabeticamente] = 2
  	else
  		session[:alfabeticamente] = 1
  	end

  	id_alfabeticamente = params[:id]
  	@products = JSON.parse(open("http://"+$API_URL+"/product_alfabeticamente/"+id_alfabeticamente).read, {:symbolize_names => true})
  
  	render(:action => "showAlfabeticamente")
  end


  def showPrec
  	if session[:precio] == 1
  		session[:precio] = 2
  	else
  		session[:precio] = 1
  	end
  	
  	id_precio = params[:id]
  	@products = JSON.parse(open("http://"+$API_URL+"/product_precio/"+id_precio).read, {:symbolize_names => true})
  
  	render(:action => "showPrecio")
  end

  def deleteProd

  	#Para borrar en caso que el producto este en el carro NO SIRVE AUN
	for product_in_car in session[:carro]
		if((product_in_car).to_i == (params[:id]).to_i)
			session[:carro].delete((params[:id]).to_i)
		end
	end

  	#Hago la peticion delete al API
  	uri = URI('http://'+$API_URL+'/product/'+params[:id])
	http = Net::HTTP.new(uri.host, uri.port)
	req = Net::HTTP::Delete.new(uri.path)
	res = http.request(req)

	redirect_to controller: 'home', action: 'index', action_do: "succesfull_deleteProduct"

  end

  def updateProdshow

	product_id = params[:id]
  	@product = JSON.parse(open("http://"+$API_URL+"/product/"+product_id).read, {:symbolize_names => true})
  	render(:action => "updateProducto")

  end

  def updateProdsend
  	uri = URI('http://'+$API_URL+'/product/'+params[:id])
  	req = Net::HTTP::Put.new(uri, 'Content-Type' => 'application/json')
	req.body = {nombre: params[:nombre], precio: params[:precio], 
				foto: params[:foto], idCategoria: ((params[:idCategoria]).to_i), 
				descripcion: params[:descripcion]}.to_json
	response = Net::HTTP.new(uri.host, uri.port).start {|http| http.request(req) }
	puts response.code

	redirect_to controller: 'home', action: 'index', action_do: "succesfull_editProduct"

  end


  def mostrarCheckout
  	@data = []
  	if(session[:carro].size != 0)
	  	uri = URI('http://'+$API_URL+'/products')
		req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
		req.body = {ids: session[:carro]}.to_json
		res = Net::HTTP.start(uri.hostname, uri.port) do |http|
			http.request(req)
		end
		@data = JSON.parse(res.body) #Aqui esta la respuesta del API
	end
  	render(:action => "mostrarCheckout")

  end

  def mostrarFactura
  	@factura = {nombre: params[:id_first_name], apellido: params[:id_last_name],
  				dir: params[:id_address_line_1], apart: params[:id_address_line_2], 
  				ciudad: params[:id_city], estado: params[:id_state],
  				cod_pos: params[:codigo_postal], tel: params[:telefono],
  				nomtar: params[:name_on_card], tarjeta: params[:card_number],
  				expM: params[:card_exp_month], expA: params[:card_exp_year],
  				cvc: params[:card_cvc]}


  	@data = []
  	if(session[:carro].size != 0)
	  	uri = URI('http://'+$API_URL+'/nueva_compra')
		req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
		req.body = {ids: session[:carro]}.to_json
		res = Net::HTTP.start(uri.hostname, uri.port) do |http|
			http.request(req)
		end
		

		uri = URI('http://'+$API_URL+'/products')
		req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
		req.body = {ids: session[:carro]}.to_json
		res = Net::HTTP.start(uri.hostname, uri.port) do |http|
			http.request(req)
		end

		@data = JSON.parse(res.body) #Aqui esta la respuesta del API

	end

	session[:carro].clear

  	render(:action => "mostrarFactura")
  end

  def createComentario

  	@user = User.find(current_user.id)
	@comment = @user.comentarios.create(:cuerpo => params[:cuerpo])

  	redirect_to controller: 'home', action: 'index', action_do: "succesfull_addComment"
  end

  def busqueda

  		uri = URI('http://'+$API_URL+'/producto_buscar')
		req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
		req.body = {query: params[:busqueda]}.to_json
		res = Net::HTTP.start(uri.hostname, uri.port) do |http|
			http.request(req)
		end

		@products = JSON.parse(res.body) #Aqui esta la respuesta del API
  		
  		render(:action => "mostrarBusqueda")
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
 <!-- Page Content -->
<div class="col-md-3">
    <p>Categorías:</p>
    <div class="list-group">
        <a href="categoria/1" class="list-group-item">Celulares</a>
        <a href="categoria/2" class="list-group-item">Videojuegos</a>
        <a href="categoria/3" class="list-group-item">Deportes</a>
    </div>

    <p>Ordena:</p>
    <div class="list-group">
    	<a href="orden/alfabeticamente/<%= session[:alfabeticamente] %>" class="list-group-item">Alfabeticamente</a>
       	<a href="orden/precio/<%= session[:precio] %>" class="list-group-item">Precio</a>
    </div>
</div>

<div class="col-md-9">
	<div class="row carousel-holder">
	    <div class="col-md-12 hidden-xs">
	        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	            <ol class="carousel-indicators">
	                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
	                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
	                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
	            </ol>
	            <div class="carousel-inner">
	                <div class="item active">
	                	<%=image_tag('carrusel/telefonos.jpg', :class => "slide-image") %>
	                </div>
	                <div class="item">
	                    <%=image_tag('carrusel/juegos.jpg', :class => "slide-image") %>
	                </div>
	                <div class="item">
	                    <%=image_tag('carrusel/deportes.jpg', :class => "slide-image") %>
	                </div>
	            </div>
	            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
	                <span class="glyphicon glyphicon-chevron-left"></span>
	            </a>
	            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
	                <span class="glyphicon glyphicon-chevron-right"></span>
	            </a>
	        </div>
	    </div>
	</div>

    <div class="row">
    	<% @products.each do |product| %>
	        <a href="/producto/<%= product[:id] %>">
		        <div class="col-xs-8 col-sm-6 col-lg-4 col-md-6">
		            <div class="thumbnail product">
		            	<div style='height:150px'>
		            		<% if product[:foto] != nil %>
		                		<img src='<%=product[:foto]%>' style='height:100%'alt="">
			                <% else %>
			                	<img src="http://placehold.it/320x150" style='height:100%' alt="">
			                <% end %>
		                </div>
		                <div class="caption">
		                    <h4>$<%=product[:precio]%></h4>
		                    <h4><%= product[:nombre] %>
		                    </h4>
		                    <% if product[:descripcion].size <= 70 %>
		                    	<p><%=product[:descripcion]%></p>
		                    <% else %>
		                    	<p>...</p>
		                    <% end %>
		                </div>
		            </div>
		        </div>
	    	</a>
	    <% end %>
    </div>
</div>

app/views/home/mostrarBusqueda.html.erb
 <!-- Page Content -->
<div class="col-md-3">
    <br><br>
    <p>Categorías:</p>
    <div class="list-group">
        <a href="/categoria/1" class="list-group-item">Celulares</a>
        <a href="/categoria/2" class="list-group-item">Videojuegos</a>
        <a href="/categoria/3" class="list-group-item">Deportes</a>
    </div>

    <p>Ordena:</p>
    <div class="list-group">
        <a href="/orden/alfabeticamente/<%= session[:alfabeticamente] %>" class="list-group-item">Alfabeticamente</a>
       	<a href="/orden/precio/<%= session[:precio] %>" class="list-group-item">Precio</a>
    </div>
</div>

<div class="col-md-9">
    <div class="row">
	    <% if @products.size > 0 %>
	    	<% @products.each do |product| %>
		        <a href="/producto/<%= product['id'] %>">
			        <div class="col-xs-8 col-sm-6 col-lg-4 col-md-6" style='min-width:290px'>
			            <div class="thumbnail product">
			            	<div style='height:150px'>
			            		<% if product['foto'] != nil %>
			                		<img src='<%=product['foto']%>' style='height:100%'alt="">
				                <% else %>
				                	<img src="http://placehold.it/320x150" style='height:100%' alt="">
				                <% end %>
			                </div>
			                <div class="caption">
			                    <h4>$<%=product['precio']%></h4>
			                    <h4><%= product['nombre'] %>
			                    </h4>
			                    <% if product['descripcion'].size <= 70 %>
			                    	<p><%=product['descripcion']%></p>
			                    <% else %>
			                    	<p>...</p>
			                    <% end %>
			                </div>
			            </div>
			        </div>
		    	</a>
		    <% end %>
	     <% else %>
	     	<br><br>
	    	<center><h2>No se encontró ningún producto relacionado a esa busqueda</h2></center>
	     <% end %>
   	</div>
</div>

app/views/home/precompra.html.erb
 
<style type="text/css">
	.delete-to-cart, .like {
	background: #e2401f;
	padding: 1.2em 1.5em;
	border: none;
	text-transform: UPPERCASE;
	font-weight: bold;
	color: white;
	-webkit-transition: background .3s ease;
	        transition: background .3s ease; }
	.delete-to-cart:hover, .like:hover {
	  background: #ed6144;
	  color: #fff; }
</style>

<center><h2>PRODUCTOS EN EL CARRO DE: <strong><%=current_user.username%></strong></h2></center>
<br>
<br>
<div class="row">
	<% sum = 0 %>
 	<% if @data.size != 0 %>
    	<% @data.each do |product| %>
    		<% sum += product['precio'] %>
    		<a href="/producto/<%= product['id'] %>">
		        <div class="col-xs-8 col-sm-6 col-lg-4 col-md-6">
		        	<div class="thumbnail product">
		            	<div style='height:150px'>
		            		<% if product['foto'] != nil %>
		                		<img src='<%= product['foto'] %>' style='height:100%'alt="">
			                <% else %>
			                	<img src="http://placehold.it/320x150" style='height:100%' alt="">
			                <% end %>
		                </div>
		                <div class="caption">
		                    <h4 class="pull-right">$<%=product['precio']%></h4>
		                    <h4><%= product['nombre'] %>
		                    </h4>
		                     <% if product['descripcion'].size <= 70 %>
		                    	<p><%=product['descripcion']%></p>
		                    <% else %>
		                    	<p>...</p>
		                    <% end %>
		                    <center><%= link_to 'Eliminar <span class="glyphicon glyphicon-shopping-cart"></span>'.html_safe, deletecar_path(:id => product['id']) , :method => :delete, :class => "delete-to-cart btn btn-default btn-sm" %></center>
		                </div>
		            </div>
		        </div>
		    </a>
	    <% end %>
	    <div class="col-sm-12 col-lg-12 col-md-12" style="margin-top:5%;">
	    	<center><h3>SUBTOTAL A PAGAR: <strong>$<%= sum %></strong></h3></center>
	    	<br>
	    	<center><%= link_to 'CONFIRMAR COMPRA', mostrarCheckout_path , :class => "btn btn-success btn-lg" %></center>
	    </div>
	<% else %>
		<center><h2>Actualmente no posee ningún producto en su carrito</h2></center>
	<% end %>
</div>
    

app/views/home/product.html.erb
<!-- ESTILO DEL PRODUCTO -->
<style type="text/css">
  img {
    max-width: 100%; }

  .preview {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-flex-direction: column;
        -ms-flex-direction: column;
            flex-direction: column; }
    @media screen and (max-width: 996px) {
      .preview {
        margin-bottom: 20px; } }

  .preview-pic {
    -webkit-box-flex: 1;
    -webkit-flex-grow: 1;
        -ms-flex-positive: 1;
            flex-grow: 1; }

  .preview-thumbnail.nav-tabs {
    border: none;
    margin-top: 15px; }
    .preview-thumbnail.nav-tabs li {
      width: 18%;
      margin-right: 2.5%; }
      .preview-thumbnail.nav-tabs li img {
        max-width: 100%;
        display: block; }
      .preview-thumbnail.nav-tabs li a {
        padding: 0;
        margin: 0; }
      .preview-thumbnail.nav-tabs li:last-of-type {
        margin-right: 0; }

  .tab-content {
    overflow: hidden; }
    .tab-content img {
      width: 100%;
      -webkit-animation-name: opacity;
              animation-name: opacity;
      -webkit-animation-duration: .3s;
              animation-duration: .3s; }

  .card {
    margin-top: 50px;
    background: #eee;
    padding: 3em;
    line-height: 1.5em; }

  @media screen and (min-width: 997px) {
    .wrapper {
      display: -webkit-box;
      display: -webkit-flex;
      display: -ms-flexbox;
      display: flex; } }

  .details {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-flex-direction: column;
        -ms-flex-direction: column;
            flex-direction: column; }

  .colors {
    -webkit-box-flex: 1;
    -webkit-flex-grow: 1;
        -ms-flex-positive: 1;
            flex-grow: 1; }

  .product-title, .price, .sizes, .colors {
    text-transform: UPPERCASE;
    font-weight: bold; }

  .checked, .price span {
    color: #5ccc30; }

  .product-title, .rating, .product-description, .price, .vote, .sizes {
    margin-bottom: 15px; }

  .product-title {
    margin-top: 0; }

  .size {
    margin-right: 10px; }
    .size:first-of-type {
      margin-left: 40px; }

  .color {
    display: inline-block;
    vertical-align: middle;
    margin-right: 10px;
    height: 2em;
    width: 2em;
    border-radius: 2px; }
    .color:first-of-type {
      margin-left: 20px; }

  .add-to-cart, .like {
    background: #ff9f1a;
    padding: 1.2em 1.5em;
    border: none;
    text-transform: UPPERCASE;
    font-weight: bold;
    color: #fff;
    -webkit-transition: background .3s ease;
            transition: background .3s ease; }
    .add-to-cart:hover, .like:hover {
      background: #b36800;
      color: #fff; }

   .delete-to-cart, .like {
    background: #e2401f;
    padding: 1.2em 1.5em;
    border: none;
    text-transform: UPPERCASE;
    font-weight: bold;
    color: white;
    -webkit-transition: background .3s ease;
            transition: background .3s ease; }
    .delete-to-cart:hover, .like:hover {
      background: #ed6144;
      color: #fff; }

  .edit-product, .like {
    background: #2ab218;
    padding: 1.2em 1.5em;
    border: none;
    text-transform: UPPERCASE;
    font-weight: bold;
    color: white;
    -webkit-transition: background .3s ease;
            transition: background .3s ease; }
    .edit-product:hover, .like:hover {
      background: #4ea03b;
      color: #fff; }

  .delete-product, .like {
    background: #f91111;
    padding: 1.2em 1.5em;
    border: none;
    text-transform: UPPERCASE;
    font-weight: bold;
    color: white;
    -webkit-transition: background .3s ease;
            transition: background .3s ease; }
    .delete-product:hover, .like:hover {
      background: #911818;
      color: #fff; }

  .not-available {
    text-align: center;
    line-height: 2em; }
    .not-available:before {
      font-family: fontawesome;
      content: "\f00d";
      color: #fff; }

  .orange {
    background: #ff9f1a; }

  .green {
    background: #85ad00; }

  .blue {
    background: #0076ad; }

  .tooltip-inner {
    padding: 1.3em; }

  @-webkit-keyframes opacity {
    0% {
      opacity: 0;
      -webkit-transform: scale(3);
              transform: scale(3); }
    100% {
      opacity: 1;
      -webkit-transform: scale(1);
              transform: scale(1); } }

  @keyframes opacity {
    0% {
      opacity: 0;
      -webkit-transform: scale(3);
              transform: scale(3); }
    100% {
      opacity: 1;
      -webkit-transform: scale(1);
              transform: scale(1); } }
</style>

<!-- FIN ESTILO DEL PERFIL -->

<div class="container">
	<div class="card">
		<div class="container-fliud">
			<div class="wrapper row">
				<div class="preview col-md-6">
					<div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1">
              <% if @product[:foto] != nil %>
                <img src='<%=@product[:foto]%>' style='max-height: 300px;'alt="">
              <% else %>
                <img src="http://placehold.it/320x150" style='height:100%' alt="">
              <% end %>
            </div>
					</div>
				</div>
				<div class="details col-md-6">
					<h3 class="product-title"><%=@product[:nombre]%></h3>
					<div class="rating">
						<div class="stars">
							<span class="fa fa-star checked"></span>
							<span class="fa fa-star checked"></span>
							<span class="fa fa-star checked"></span>
							<span class="fa fa-star"></span>
							<span class="fa fa-star"></span>
						</div>
						<span class="review-no"><%=@product[:cantVendida]%> producto(s) vendido(s)</span>
					</div>
					<h4 class="price">Descripción del producto:</h4>
					<p class="product-description"><%=@product[:descripcion]%></p>
					<h4 class="price">precio: <span>$<%=@product[:precio]%></span></h4>
					<div class="action">
					 <% if user_signed_in? %>
					 	<% if !session[:carro].include?(@product[:id]) %>
					 		<%= link_to 'Añadir <span class="glyphicon glyphicon-shopping-cart"></span>'.html_safe, addcar_path , :method => :post, :class => "add-to-cart btn btn-default"%>
              <%= link_to 'Editar <span class="glyphicon glyphicon-edit"></span>'.html_safe, updateProductoShow_path , :method => :get, :class => "edit-product btn btn-default"%>
              <%= link_to 'Eliminar <span class="glyphicon glyphicon-trash"></span>'.html_safe, deleteProducto_path , :method => :delete, :class => "delete-product btn btn-default"%>
					 	<% else %>
					 		<%= link_to 'Eliminar <span class="glyphicon glyphicon-shopping-cart"></span>'.html_safe, deletecar_path , :method => :delete, :class => "delete-to-cart btn btn-default"%>
              <%= link_to 'Editar <span class="glyphicon glyphicon-edit"></span>'.html_safe, updateProductoShow_path , :method => :get, :class => "edit-product btn btn-default"%>
              <%= link_to 'Eliminar <span class="glyphicon glyphicon-trash"></span>'.html_safe, deleteProducto_path , :method => :delete, :class => "delete-product btn btn-default"%>
					 	<% end %>
					 <% else %>
						<button disabled class="add-to-cart btn btn-default" type="button">Añadir al carro <span class="glyphicon glyphicon-shopping-cart"></span></button>
					  <% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/home/registro.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="headers_text panel-title">
            <strong>Registro de usuario vía API:</strong>
          </h3>
        </div>
        <div class="headers_black_text panel-body">
          <form id="form_id" method="POST">
          <div class="col-md-12">
         
                <h2>
                  <strong><label>Email</label></strong><br>

                </h2>
                <p>
                  <input class="form-control" type="email" value="" name="email" id="user_email">
                </p>
                <h2>
                   <strong>Contraseña</strong>

                </h2>
                <p>
                   <input autocomplete="off" class="form-control" type="password" name="password" id="user_password">
                </p>
                </div>
              <div class="panel-footer">
                <p> <%= link_to 'Registrar', registershowsend_path, value: "Guardar", :class => "btn btn-success", :onclick => "$('#form_id').submit()" %></p>
              </div>
          </form>
          
          
        </div>

      </div>
    </div>
  </div>
</div>

 <%= link_to 'Registrate normal', new_user_registration_path %>


 <!-- CREO QUE PA LO DE LA SESION DEL DEVISE ES USAR EL /sign_in PASANDOLE LOS PARAMETROS -->